version: '3.8'

services:
  db-e2e:
    image: postgres:latest
    env_file:
      - docker.env
    ports:
      - "5434:5432"
    networks:
      - my_network

  nestjs-api-e2e:
    build:
      dockerfile: Dockerfile.e2e
    ports:
      - '3000:3000'
    env_file:
      - e2e.env
    depends_on:
      - db-e2e
    networks:
      - my_network
    volumes:
      - type: tmpfs
        target: /app/data

networks:
  my_network:
    driver: bridge